Assignment2Final-war/src/java/au/uts/edu/aip/controller/AccountController.java
package au.uts.edu.aip.controller;

import au.edu.uts.aip.domain.AccountBean;
import ad.edu.uts.aip.data.Account;
import java.io.Serializable;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.*;
import javax.ejb.*;
import javax.faces.application.*;
import javax.faces.context.*;
import javax.faces.view.ViewScoped;
import javax.inject.*;
import javax.servlet.*;

/**
 * AccountController is the presentation logic that call from accountBean
 * @author 17
 */
@Named
@ViewScoped
public class AccountController implements Serializable { 
    private String userName;
    private String password;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    @EJB 
    private AccountBean accountBean;
    private Account account = new Account();

    public Account getAccount() {
        return account;
    }
    
    /**
     * get current account by sessionController
     * @param sessionController 
     */
    public void loadAccount(SessionController sessionController) {
        account=sessionController.getAccount();
    }
    
    /**
     * save new record into account database
     * get hashed password
     * insert record into account
     * display warning information
     */
    public String save( ) throws NoSuchAlgorithmException {
        //Check whether username exist      
        if(accountBean.getAccountByUserName(account.getUserName())!=null)
        {
            showError("UserName exists!");
            return null;
        }
        else
        {   
            //get hashed password and set
            String currentPassword= hash256(account.getPassword());         
            account.setPassword(currentPassword);
            accountBean.createAccount(account);       
            return "registersucceed?faces-redirect=true";            
        }
    }  
    
    /**
     * configure hash password
     * return hashed password 
     */
    public static String hash256(String data) throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        md.update(data.getBytes());
        return bytesToHex(md.digest());
    }
    
   /**
    * get hash value
    * @param bytes
    * @return 
    */
    public static String bytesToHex(byte[] bytes) {
        StringBuffer result = new StringBuffer();
        for (byte byt : bytes)
        {
            result.append(Integer.toString((byt & 0xff) + 0x100, 16).substring(1));
        }
        return result.toString();
    }
    
    /**
     * Adds a message to the current faces context, so that it will appear in
     * @param message the text of the error message to show the user
     */
    private void showError(String message) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(message));
    }
    
    /**
    * List all the accounts
    * @return list
    */
    public List<Account> getPeople() {
        return accountBean.findAllAccount(); 
    }
    
    /**
     * login method,users can log in 
     * @param sessionController
     * @return
     * @throws NoSuchAlgorithmException 
     */
    public String login(SessionController sessionController) throws NoSuchAlgorithmException  {
         //get the current account
         Account currentAccount=accountBean.getAccountByUserName(userName);
         
         //differnt subscription user can go into different page
         if(currentAccount!=null&&currentAccount.getPassword().equals(hash256(password)))
         {
             sessionController.setAccount(currentAccount);
             
             if(currentAccount.getSubscription().equals("FREE"))
             {
                  return "/listFree?faces-redirect=true";
             }
             else if (currentAccount.getSubscription().equals("STANDARD"))
             {
                 return "/listStardard?faces-redirect=true";
             }
             else if (currentAccount.getSubscription().equals("PREMIUM"))
             {
                 return "/list?faces-redirect=true";
             }
             else
                 return "/listAdmin?faces-redirect=true";
         }
         else
         {
             //show error when log in 
             showError("Incorrect username or password (or you may not have properly configured aipRealm)");
             showError("Click log out to re-log in ");  
             return null;
         }     
     
     }
    
    /**
     * update changes after editing it
     * @return to different pages according to subscription
     */
    public String saveChanges() {
        accountBean.updateAccount(account);
        if(account.getSubscription().equals("FREE"))
        {
            return "listFree?faces-redirect=true";
        }
        else if(account.getSubscription().equals("STANDARD"))
        {
            return "listStardard?faces-redirect=true";
        }
        else if(account.getSubscription().equals("PREMIUM"))
        {
            return "list?faces-redirect=true";
        }
        else
        {
            return null;
        }            
   }

    /**
     * Logs out the current user 
     * current user in the given session controller.
     * @param sessionController
     * @throws ServletException 
     */
    public String logout(SessionController sessionController) throws ServletException  {
        sessionController.setAccount(null);
        return "/login?faces-redirect=true";
    }
   
}

Assignment2Final-war/web/deletefeedback.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <f:metadata>
        <f:viewAction action="#{feedbackController.loadFeedback(param.id)}"/>
    </f:metadata>
    <h:head>
        <title>Delete Record</title>
    </h:head>
    <div align="center">
        <h1>Subject Feedback</h1> 
    </div>
    <hr style="border-width: 2px"/>
    <h:body>
        <div align="center">  
            <h2>Delete Feedback</h2> 
        </div>
        <div align="center" style="color: blue">  
            <p>Are you sure you want to delete?</p>
        </div>
        <div align="center">
            <h:form>
                <p>
                <label>Subject Name: 
                    <h:outputText value="#{feedbackController.feedback.subjectName}"/>
                </label>
                </p>
                <p>
                <label>Content:
                    <h:outputText value="#{feedbackController.feedback.content}"/>
                </label>
                </p>
                <p>
                <h:inputHidden value="#{feedbackController.feedback.id}"/>
                <h:button value="Cancel" outcome="list"/>  &nbsp;&nbsp; 
                <h:commandButton value="Delete" action="#{feedbackController.deleteFeedback()}"/>
                </p>
            </h:form> 
        </div>
    </h:body>
</html>


Assignment2Final-war/web/editfeedback.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <f:metadata>
        <f:viewAction action="#{feedbackController.loadFeedback(param.id)}"/>
    </f:metadata>
    <h:head>
        <div align="center"><h1>Subject Feedback</h1> </div>
        <hr style="border-width: 2px"/>
        <title>Feedback List</title>
    </h:head>
    <h:body>
        <div align="center">
        <h1>Edit Feedback</h1>
        <h:form>
            <p>
                <label>Subject Name:
                    <h:inputText id="subject" value="#{feedbackController.feedback.subjectName}" />
                </label>
            </p>
            <p>
                <label> Content:
                    <h:inputTextarea id="content" value="#{feedbackController.feedback.content}" />
                </label>
            </p>
            <p>
                <h:inputHidden value="#{feedbackController.feedback.id}"/>
                <h:inputHidden value="#{feedbackController.feedback.userName}"/>
                <h:button value="Cancel" outcome="list"/>  &nbsp;&nbsp; 
                <h:commandButton value="Save" action="#{feedbackController.saveChanges}"/>
            </p>
        </h:form>
        </div>
    </h:body>
</html>


Assignment2Final-war/web/feedbackpage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
       xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>FeedBack</title>
    </h:head>
    <h:body>
        <div align="center"><h1>Subject Feedback</h1> </div>
        <hr style="border-width: 2px"/>
        <h:form>
            <div align="center">
                <label>
                    <h1> Subject Name</h1>           
                    <h:inputText
                    id="subject" 
                    value="#{feedbackController.feedback.subjectName}" />
                </label>
            </div>
            <div align="center">
                <label> 
                    <h1>Feedback Content</h1>
                </label>
            </div>
            <div align="center">
                <h:inputTextarea 
                    id="content" 
                    value="#{feedbackController.feedback.content}" />
            </div>
                &nbsp;&nbsp;
            <div align="center">
                <h:commandButton value="Save" action="#{feedbackController.save(sessionController)}"/>
                                                 &nbsp;&nbsp; 
                <h:button value="Cancel" outcome="list"/> 
            </div>                     
        </h:form>
    </h:body>
</html>


Assignment2Final-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Student Feedback</title>
    </h:head>
    <h:body>
        <div align="center"><h1><h:outputText value="Subject Feedback" /></h1></div>
        <hr style="border-width: 2px"/>
        <div align="center"><h:link value="Log in Page" outcome="login"/></div>
    </h:body>
</html>

Assignment2Final-war/web/list.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Feedback List</title>
    </h:head>
    <h:body>
        <div align="center"><h1>Subject Feedback</h1> </div>
        <hr style="border-width: 2px"/>
        <div align="center">
            <h:dataTable border="1" cellpadding="20" var="feedback"  value="#{feedbackController.feedbacks}">
                <h:column>
                    <f:facet name="header">
                    Subject Name
                    </f:facet>
                <h:outputText value="#{feedback.subjectName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                    Feedback Content
                    </f:facet>
                <h:outputText value="#{feedback.content}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                 User Name
                    </f:facet>
                <h:outputText value="#{feedback.userName}"/>
                </h:column>                  
                <h:column>
                    <f:facet name="header">
                    Delete
                    </f:facet>
                    <h:link value="Delete" outcome="deletefeedback">
                        <f:param name="id" value="#{feedback.id}"/>
                    </h:link>
                </h:column>
                <h:column>
                    <f:facet name="header">
                    Edit
                    </f:facet>
                    <h:link value="Edit" outcome="editfeedback">
                        <f:param name="id" value="#{feedback.id}"/> 
                    </h:link>
                </h:column>           
            </h:dataTable>
        </div>
        <div align="center">
            <h:form>
                <p>
                    <h:link value="New Feedback" outcome="feedbackpage"/>
                </p>                              
                <p>
                    <h:commandButton value="Log Out " action="#{accountController.logout(sessionController)}"/>
                    <h:link value="Change Subscription" outcome="updateSubscription"/>
                </p>
            </h:form>
        </div>
    </h:body>
</html>


Assignment2Final-war/web/listAdmin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Feedback List</title>
    </h:head>
    <h:body>
        <div align="center"><h1>Administrator Management</h1> </div>
        <hr style="border-width: 2px"/>
        <div align="center">
            <h:dataTable border="1" cellpadding="20" var="person"  value="#{accountController.people}">
            <h:column>
                <f:facet name="header">
                    User Name
                </f:facet>
                <h:outputText value="#{person.userName}"/>
            </h:column>
                <h:column>
                    <f:facet name="header">
                     Subscription
                    </f:facet>
                <h:outputText value="#{person.subscription}"/>
            </h:column>        
            </h:dataTable>
        </div>
        <div align="center">
            <h:form>                             
                <p>
                    <h:commandButton value="Log Out " action="#{accountController.logout(sessionController)}"/>
                </p>
            </h:form>
        </div>
    </h:body>
</html>


Assignment2Final-war/web/listFree.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Feedback List</title>
    </h:head>
    <h:body>
        <div align="center"><h1>Subject Feedback</h1> </div>
        <hr style="border-width: 3px"/>
        <div align="center">
            <h:dataTable border="1" cellpadding="20" var="feedback"  value="#{feedbackController.feedbacks}">
                <h:column>
                    <f:facet name="header">
                    Subject Name
                    </f:facet>
                <h:outputText value="#{feedback.subjectName}"/>
                </h:column>       
                <h:column>
                    <f:facet name="header">
                    Feedback Content
                    </f:facet>
                <h:outputText value="#{feedback.content}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                 User Name
                    </f:facet>
                <h:outputText value="#{feedback.userName}"/>
                </h:column>                  
            </h:dataTable>
        </div>
        <div align="center">
            <h:form>                          
                <p>
                    <h:commandButton value="Log Out " action="#{accountController.logout(sessionController)}"/>         
                </p>
                <p>
                    <h:link value="UpdateSubscription" outcome="updateSubscription"/>
                </p>
            </h:form>
        </div>
    </h:body>
</html>

Assignment2Final-war/web/listStardard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Feedback List</title>
    </h:head>
    <h:body>
        <div align="center"><h1>Subject Feedback</h1> </div>
        <hr style="border-width: 2px"/>
        <div align="center">
            <h:dataTable border="1" cellpadding="20" var="feedback"  value="#{feedbackController.feedbacks}">
                <h:column>
                    <f:facet name="header">
                    Subject Name
                    </f:facet>
                    <h:outputText value="#{feedback.subjectName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                    Feedback Content
                    </f:facet>
                    <h:outputText value="#{feedback.content}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                 User Name
                    </f:facet>
                    <h:outputText value="#{feedback.userName}"/>
                </h:column>                       
            </h:dataTable>
        </div>
        <div align="center">
            <h:form>
                <p>
                    <h:link value="New Feedback" outcome="feedbackpage"/>
                </p>                              
                <p>                  
                    <h:link value="Change Subscription" outcome="updateSubscription"/>                  
                </p>
                <p>
                    <h:commandButton value="Log Out " action="#{accountController.logout(sessionController)}"/>
                </p>
            </h:form>
        </div>
    </h:body>
</html>

Assignment2Final-war/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Subject Feedback Login</title>     
    </h:head>
    <h:body>
        <div align="center">
            <h1>Subject Feedback</h1> 
        </div>
        <hr style="border-width: 2px"/>
        <div align="center">
            <h:form>
                <h2>Log In</h2>         
                <p>
                    <label>Student ID <h:inputText value="#{accountController.userName}"/> </label>
                </p>
                <p>
                    <label>Password <h:inputSecret value="#{accountController.password}"/></label>
                </p> 
                <h:messages style="color: red;"/>
                <p>
                    <h:commandButton value="Log In " action="#{accountController.login(sessionController)}"/>
                </p>  
                <p>
                    <h:commandButton value="Log Out" action="#{accountController.logout(sessionController)}"/>
                </p>
                <p>
                    <h:link value="Register" outcome="register"/>
                </p>
            </h:form>
        </div>
    </h:body>
</html>
                
   


Assignment2Final-war/web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Register</title>
    </h:head>
    <h:body>
        <div align="center"><h1>Register</h1> </div>
        <hr style="border-width: 2px"/>   
        <div align="center">
            <h:form>
                <p>
                    <label>Username Name:
                        <h:inputText id="userName" value="#{accountController.account.userName}" />
                    </label>
                </p>
                <p>
                    <label>  Subscription               
                        <h:selectOneRadio id="subscription" value="#{accountController.account.subscription}">
                            <f:selectItem itemValue="FREE" itemLabel="Free" />
                            <f:selectItem itemValue="STANDARD" itemLabel="Standard"/>
                            <f:selectItem itemValue="PREMIUM" itemLabel="Premium" />
                            <f:selectItem itemValue="ADMIN" itemLabel="Admin"/>
                        </h:selectOneRadio>
                    </label>
                </p>
                <p>
                    <label>Password:
                        <h:inputText id="npassword" value="#{accountController.account.password}"/>
                    </label>
                </p>             
                <h:commandButton value="Save" action="#{accountController.save()}"/>
          &nbsp;&nbsp; 
                 <h:button value="Cancel" outcome="login"/> 
            </h:form>
        </div>
    </h:body>
</html>


Assignment2Final-war/web/registersucceed.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Register Succeed</title>
    </h:head>
    <h:body>
        <div align="center">
            <h1>Register</h1>
        </div>   
        <hr style="border-width: 2px"/>   
        <div align="center">
            <h2>Register Succeed!</h2>
            <h:link value="Return" outcome="login"/>    
        </div>       
    </h:body>
</html>


Assignment2Final-war/web/updateSubscription.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <f:metadata>
        <f:viewAction action="#{accountController.loadAccount(sessionController)}"/>
    </f:metadata>
    <h:head>
        <div align="center"><h1>Subject Feedback</h1> </div>
        <hr style="border-width: 2px"/>
        <title>Subscription List</title>
    </h:head>
    <h:body>
        <div align="center">
            <h1>Update Subscription</h1>
            <h:form>
                <p>
                    <label>  Subscription               
                        <h:selectOneRadio id="subscription" value="#{accountController.account.subscription}">
                            <f:selectItem itemValue="FREE" itemLabel="Free" />
                            <f:selectItem itemValue="STANDARD" itemLabel="Standard"/>
                            <f:selectItem itemValue="PREMIUM" itemLabel="Premium" />
                        </h:selectOneRadio>
                    </label>
                </p>
                <p>
                    <h:inputHidden value="#{accountController.account.userName}"/>
                    <h:inputHidden value="#{accountController.account.password}"/>
                    <h:inputHidden value="#{feedbackController.feedback.id}"/>
                    <h:button value="Cancel" outcome="list"/>  &nbsp;&nbsp; 
                    <h:commandButton value="Save" action="#{accountController.saveChanges}"/>
                </p>
            </h:form>
        </div>
    </h:body>
</html>
